<a href="https://colab.research.google.com/github/shubh593/Basic-Machine-Learning/blob/main/Machine_Learning3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/synthetic_dataset.csv')
df.head()

  Category   Price    Rating         Stock  Discount
0      NaN  5548.0  1.870322           NaN       0.0
1      NaN  3045.0  4.757798           NaN      38.0
2      NaN  4004.0       NaN      In Stock       0.0
3      NaN  4808.0  1.492085           NaN      33.0
4      NaN  1817.0       NaN  Out of Stock      23.0

In [ ]:
df.isnull().sum()

Category    2748
Price        174
Rating      2050
Stock       1352
Discount     392
dtype: int64

In [ ]:
df.tail()

     Category   Price    Rating         Stock  Discount
4357      NaN  4436.0  4.728335           NaN      49.0
4358        B  6236.0       NaN  Out of Stock       4.0
4359      NaN  3283.0       NaN  Out of Stock       9.0
4360        D  2999.0  4.425995           NaN      40.0
4361      NaN     NaN  2.184471           NaN       0.0

In [ ]:
df.describe()

             Price       Rating     Discount
count  4188.000000  2312.000000  3970.000000
mean   5016.970630     3.038293    24.516625
std    2839.984813     1.143074    14.347164
min     102.000000     1.000366     0.000000
25%    2628.250000     2.069490    12.000000
50%    4996.500000     3.082060    25.000000
75%    7418.000000     4.008620    37.000000
max    9999.000000     4.997818    49.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4188 non-null   float64
 2   Rating    2312 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [ ]:
df = df.drop(['Category'],axis=1)
df.head()

    Price    Rating         Stock  Discount
0  5548.0  1.870322           NaN       0.0
1  3045.0  4.757798           NaN      38.0
2  4004.0       NaN      In Stock       0.0
3  4808.0  1.492085           NaN      33.0
4  1817.0       NaN  Out of Stock      23.0

                   By Mean

In [ ]:
# putting null values by mean of it
df['Price']=df['Price'].fillna(df['Price'].mean())
df['Rating']=df['Rating'].fillna(df['Rating'].mean())

In [ ]:
df.head()

    Price    Rating         Stock  Discount
0  5548.0  1.870322           NaN       0.0
1  3045.0  4.757798           NaN      38.0
2  4004.0  3.038293      In Stock       0.0
3  4808.0  1.492085           NaN      33.0
4  1817.0  3.038293  Out of Stock      23.0

In [ ]:
# Lets assume price over rating
x=df['Rating']
y=df['Price']

In [ ]:
# By defining B1 and B0
x_mean=df['Price'].mean()
y_mean=df['Rating'].mean()
print(x_mean)
print(y_mean)

5016.970630372492
3.038292519108619

In [ ]:
B1=((x-x_mean)*(y-y_mean)).sum()/((x-x_mean)**2).sum()
B0=y_mean-B1*x_mean
print(B1)
print(B0)

-0.9999985760003206
5020.001778727032

In [ ]:
y_predicted=B0 + B1*x

In [ ]:
y_predicted

0       5018.131459
1       5015.243987
2       5016.963491
3       5018.509696
4       5016.963491
           ...
4357    5015.273450
4358    5016.963491
4359    5016.963491
4360    5015.575790
4361    5017.817311
Name: Rating, Length: 4362, dtype: float64

In [ ]:
df.head()

    Price    Rating         Stock  Discount
0  5548.0  1.870322           NaN       0.0
1  3045.0  4.757798           NaN      38.0
2  4004.0  3.038293      In Stock       0.0
3  4808.0  1.492085           NaN      33.0
4  1817.0  3.038293  Out of Stock      23.0

In [ ]:
error = y - y_predicted
error

0        529.868541
1      -1970.243987
2      -1012.963491
3       -210.509696
4      -3199.963491
           ...
4357    -579.273450
4358    1219.036509
4359   -1733.963491
4360   -2016.575790
4361      -0.846680
Length: 4362, dtype: float64

In [ ]:
mean_squared_error = (error**2).mean()
print(np.sqrt(mean_squared_error))

2782.4454343149673

**                    By Mode**

In [ ]:

# 1. Calculate the mode as an integer scalar
price_mode = int(df['Price'].mode()[0])
rating_mode= int(df['Rating'].mode()[0])
print(price_mode)
print(rating_mode)

5016
3

In [ ]:
# Putting values by Mode of it
df['Mode_Price']=df['Price'].fillna(price_mode).astype(int)
df['Mode_Rating']=df['Rating'].fillna(rating_mode).astype(int)

In [ ]:
# Lets assume price over rating
x_mode=df['Mode_Rating']
y_mode=df['Mode_Price']

In [ ]:
# By defining B1 and B0
x_mode_mean=x_mode.mean()
y_mode_mean=y_mode.mean()
print(x_mode_mean)
print(y_mode_mean)

2.753782668500688
5016.931911966987

In [ ]:
B1=((x_mode-x_mode_mean)*(y_mode-y_mode_mean)).sum()/((x_mode-x_mode_mean)**2).sum()
B0=y_mode_mean-B1*x_mode_mean
print(B1)
print(B0)

24.33230057121412
4949.926044369228

In [ ]:
y_mode_predicted=B0 + B1*x
y_mode_predicted

0       4995.435282
1       5065.694217
2       5023.854691
3       4986.231902
4       5023.854691
           ...
4357    5064.977312
4358    5023.854691
4359    5023.854691
4360    5057.620691
4361    5003.079257
Name: Rating, Length: 4362, dtype: float64

In [ ]:
mode_error=y-y_mode_predicted
mode_error

0        552.564718
1      -2020.694217
2      -1019.854691
3       -178.231902
4      -3206.854691
           ...
4357    -628.977312
4358    1212.145309
4359   -1740.854691
4360   -2058.620691
4361      13.891373
Length: 4362, dtype: float64

In [ ]:
# Mean error
mean_squared_error=(error**2).mean()
print(np.sqrt(mean_squared_error))

2782.4454343149673

In [ ]:
# Mode Error
mode_mse=(mode_error**2).mean()
print(np.sqrt(mode_mse))

2782.2078453855875

In [ ]:
# Forward fill
df['Price_ffill'] = df['Price'].ffill()
df['Rating_ffill'] = df['Rating'].ffill()

# Backward fill
df['Price_bfill'] = df['Price'].bfill()
df['rating_bfill']= df['Rating'].bfill()

In [ ]:
df.head()

,Price,Rating,Stock,Discount,Mode_Price,Mode_Rating,Price_ffill,Rating_ffill,Price_bfill,rating_bfill
0,5548.0,1.870322,NaN,0.0,5548,1,5548.0,1.870322,5548.0,1.870322
1,3045.0,4.757798,NaN,38.0,3045,4,3045.0,4.757798,3045.0,4.757798
2,4004.0,3.038293,In Stock,0.0,4004,3,4004.0,3.038293,4004.0,3.038293
3,4808.0,1.492085,NaN,33.0,4808,1,4808.0,1.492085,4808.0,1.492085
4,1817.0,3.038293,Out of Stock,23.0,1817,3,1817.0,3.038293,1817.0,3.038293

In [ ]:
x_ffill=df['Rating_ffill']
y_ffill=df['Price_ffill']

In [ ]:
x_ffill_mean=df['Price_ffill'].mean()
y_ffill_mean=df['Rating_ffill'].mean()
print(x_ffill_mean)
print(y_ffill_mean)

5016.970630372492
3.038292519108619

In [ ]:
B1_fill=((x_ffill-x_ffill_mean)*(y_ffill-y_ffill_mean)).sum()/((x_ffill-x_ffill_mean)**2).sum()
B0_fill=y_ffill_mean-B1_fill*x_ffill_mean
print(B1_fill)
print(B0_fill)

-0.9999985760003206
5020.001778727032

In [ ]:
ffill_predicted=B0_fill + B1_fill*x_ffill
ffill_predicted

0       5018.131459
1       5015.243987
2       5016.963491
3       5018.509696
4       5016.963491
           ...
4357    5015.273450
4358    5016.963491
4359    5016.963491
4360    5015.575790
4361    5017.817311
Name: Rating_ffill, Length: 4362, dtype: float64

In [ ]:
ffill_error=y_ffill - ffill_predicted

In [ ]:
mse_ffill=(ffill_error**2).mean()
print(np.sqrt(mse_ffill))

2782.4454343149673